In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random

pd.options.mode.chained_assignment = None

In [4]:
dataset = pd.read_excel('Perceptron.xlsx')

for i in range(len(dataset['Class'])):
    if dataset['Class'][i] == 'Bomber':
        dataset['Class'][i] = -1
    else:
        dataset['Class'][i] = 1
        
print(dataset)

   Mass  Speed Class
0   1.0    0.1    -1
1   2.0    0.2    -1
2   0.1    0.3     1
3   2.0    0.3    -1
4   0.2    0.4     1
5   3.0    0.4    -1
6   0.1    0.5     1
7   1.5    0.5    -1
8   0.5    0.6     1
9   1.6    0.7     1


In [5]:
# data
x = dataset[['Mass', 'Speed']].to_numpy()
x = np.insert(x, 0, 1, axis= 1)
w = np.random.randn(3, 1)
y = dataset['Class'].to_numpy()

# hyper-parameters
learning_rate = 0.1
epochs = 100

print('x = ' + str(x))
print('w = ' + str(w))
print('y = ' + str(np.transpose(y)))

x = [[1.  1.  0.1]
 [1.  2.  0.2]
 [1.  0.1 0.3]
 [1.  2.  0.3]
 [1.  0.2 0.4]
 [1.  3.  0.4]
 [1.  0.1 0.5]
 [1.  1.5 0.5]
 [1.  0.5 0.6]
 [1.  1.6 0.7]]
w = [[ 0.85283076]
 [-0.22579659]
 [-0.61486061]]
y = [-1 -1 1 -1 1 -1 1 -1 1 1]


In [6]:
def train(x, y, w, learnin_rate, epochs):
    
    performance = 0
    epoch_counter = 0

    while epochs > 0:
        performance_counter = 0
        epoch_counter += 1
        for i in range(len(x)):
            z = np.dot(x[i].reshape(1, 3), w)
            y_estimate = np.sign(z)

            error = y[i] - y_estimate

            w = w + learning_rate * error * x[i].reshape(1, 3).T

            if y_estimate == y[i]:
                performance_counter += 1

        if performance_counter == len(x):
            performance = 1
            print("Accuracy is finally 100%! Congrats!")
            print("Model has reached 100% accuracy after " + str(epoch_counter) + " epochs!")
            break
        else:
            performance = performance_counter / len(x)

        print("Accuracy is " + str(performance) + " on epoch " + str(epoch_counter))

        epochs -= 1

In [7]:
def predict(mass, speed):
    x_test = np.array([1, mass, speed]).reshape(1, 3)
    z_test = np.dot(x_test, w)
    y_predicted = np.sign(z_test)
    
    if y_predicted == -1:
        return "Bomber"
    elif y_predicted == 1:
        return "Fighter"
    else:
        return None

In [8]:
train(x, y, w, 0.1, 50)
print("Final weight: " + str(w))

Accuracy is 0.8 on epoch 1
Accuracy is 0.8 on epoch 2
Accuracy is 0.6 on epoch 3
Accuracy is 0.6 on epoch 4
Accuracy is 0.8 on epoch 5
Accuracy is 0.7 on epoch 6
Accuracy is 0.8 on epoch 7
Accuracy is 0.8 on epoch 8
Accuracy is 0.7 on epoch 9
Accuracy is 0.8 on epoch 10
Accuracy is 0.8 on epoch 11
Accuracy is 0.7 on epoch 12
Accuracy is 0.8 on epoch 13
Accuracy is 0.9 on epoch 14
Accuracy is finally 100%! Congrats!
Model has reached 100% accuracy after 15 epochs!
Final weight: [[ 0.85283076]
 [-0.22579659]
 [-0.61486061]]


In [12]:
test_index = 8

prediction = predict(x[test_index][1], x[test_index][2])
print(prediction)
print(x[test_index])
print(y[test_index])

Fighter
[1.  0.5 0.6]
1
